### ISSUE TITLE
openrazer-daemon fails to start

### ISSUE THREAD

**Issue by maalaria** [openrazer/razer-drivers#1777]
### Distribution

Ubuntu 20.04.4 LTS 
(as VM in VirtualBox)

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

When plugging my Razer Viper 8k in, Polychromatic gives me "Unrecognised Device" (Device ID etc is correct, though). Following the "Troubleshoot" button I started the daemon from command line ```openrazer-daemon -Fv``` which gives the following output:

```
Starting daemon.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/daemonize.py", line 245, in start
    self.action(*privileged_action_result)
  File "/usr/bin/openrazer-daemon", line 140, in run_daemon
    daemon = RazerDaemon(verbose=args.verbose,
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 83, in __init__
    self.read_persistence(persistence_file)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 303, in read_persistence
    self._persistence.read(persistence_file)
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/marius/.config/openrazer/persistence.conf', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

Stopping daemon.
```

**Comment by z3ntu** [comment]
Remove the file `/home/marius/.config/openrazer/persistence.conf` and it should work again.

@lah7 I think it's becoming a good idea to try-catch this file and recreate it from scratch if reading fails... What do you think?

**Comment by lah7** [comment]
Yes, agreed. It's strange why this file ends up corrupt, but a reset persistence configuration would be much better then the daemon failing to start 👍🏼
