### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by AlexTheProgrammer23** [openrazer/razer-drivers#2331]
### Affected Device / PID

None

### Operating System / Version

ChromeOS Version 129.0.6668.110 (Official Build) (64-bit)

### Kernel Version

6.6.46-04024-g9e7e147b4900

### OpenRazer Version

N/A

### Support Checklist

- [X] My user was added to the plugdev group.
- [X] I have rebooted and the problem persists.
- [X] I looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page and it did not solve the problem.

### Symptoms

- [ ] Uninstalling OpenRazer fixes the problem
- [ ] Re-plugging the device fixes the problem
- [ ] It worked before a system/kernel update.
- [ ] Only a problem if the daemon is running.
- [ ] Only a problem from power up or a reboot.
- [ ] I'm dual booting with Windows.
- [ ] Intermittent or erratic problem.
- [ ] My device is missing a feature.

### Please describe the issue

When I run `sudo add-apt-repository ppa:openrazer/stable` or `sudo add-apt-repository ppa:openrazer/daily`  it returns
```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
```
I'm not sure what this error is, but it is preventing me from installing.

**Comment by z3ntu** [comment]
I don't know what ChromeOS is doing there, or how you could use OpenRazer there, but please ask in the support channels for your OS, this stacktrace is not from OpenRazer at all.

But I wonder if it's possible at all to install OpenRazer on ChromeOS - I don't think so?
